name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: { node-version: 18 }

      - run: npm install
      - run: npm run build

      - run: npm install @capacitor/cli@5.7.8 @capacitor/android@5.7.8 --legacy-peer-deps

      - run: |
          npx cap sync
          npx cap add android

      - run: |
          cd android
          ./gradlew assembleDebug

      - run: mv android/app/build/outputs/apk/debug/*.apk ./GrowGardenVerse.apk

      - run: |
          echo "=== Contenu racine avant upload ==="
          ls -la .

      - uses: actions/upload-artifact@v4
        with:
          name: GrowGardenVerse
          path: GrowGardenVerse.apk